#!/bin/bash

ORANGE='\e[0;33m'
NC='\e[0;m'


echo_cmd(){
	echo -e "\t${ORANGE}$1${NC}"
}

cd ~/Documents/robot_compagnon/
#update git
sudo git pull

if [ $# > 1 ]; then
  if [ "$1" = "test" ]; then
    cd Code
    if [ "$2" = "-d" ]; then
      echo "python3 Code/test.py"
    fi
    python3 test.py
    cd ..
    if [ "$2" = "-d" ]; then
      echo "bash script.sh"
    fi
    sudo bash script.sh
  elif [ "$1" = "main" ]; then
    cd Code
    if [ "$2" = "-d" ]; then
      echo "python3 Code/main.py"
    fi
    python3 main.py
    cd ..
  else
    echo "commande :"
    echo_cmd "run test"
  fi
else
    echo "commande :"
    echo_cmd "run test"
    echo_cmd "run main"
    echo_cmd '[CMD] -d #pour le débug'
fi

